In [1]:
import pandas as pd

In [5]:
poblacion=pd.read_csv('POB_TOT.csv', header=0)

In [7]:
poblacion

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54608.0,55811.0,56682.0,57475.0,58178.0,58782.0,...,102112.0,102880.0,103594.0,104257.0,104874.0,105439.0,105962.0,106442.0,106585.0,106537.0
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130692579.0,134169237.0,137835590.0,141630546.0,145605995.0,149742351.0,...,552530654.0,567891875.0,583650827.0,600008150.0,616377331.0,632746296.0,649756874.0,667242712.0,685112705.0,702976832.0
2,Afghanistan,AFG,"Population, total",SP.POP.TOTL,8622466.0,8790140.0,8969047.0,9157465.0,9355514.0,9565147.0,...,30466479.0,31541209.0,32716210.0,33753499.0,34636207.0,35643418.0,36686784.0,37769499.0,38972230.0,40099462.0
3,Africa Western and Central,AFW,"Population, total",SP.POP.TOTL,97256290.0,99314028.0,101445032.0,103667517.0,105959979.0,108336203.0,...,376797999.0,387204553.0,397855507.0,408690375.0,419778384.0,431138704.0,442646825.0,454306063.0,466189102.0,478185907.0
4,Angola,AGO,"Population, total",SP.POP.TOTL,5357195.0,5441333.0,5521400.0,5599827.0,5673199.0,5736582.0,...,25188292.0,26147002.0,27128337.0,28127721.0,29154746.0,30208628.0,31273533.0,32353588.0,33428486.0,34503774.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,Kosovo,XKX,"Population, total",SP.POP.TOTL,947000.0,966000.0,994000.0,1022000.0,1050000.0,1078000.0,...,1807106.0,1818117.0,1812771.0,1788196.0,1777557.0,1791003.0,1797085.0,1788878.0,1790133.0,1786038.0
262,"Yemen, Rep.",YEM,"Population, total",SP.POP.TOTL,5542459.0,5646668.0,5753386.0,5860197.0,5973803.0,6097298.0,...,26223391.0,26984002.0,27753304.0,28516545.0,29274002.0,30034389.0,30790513.0,31546691.0,32284046.0,32981641.0
263,South Africa,ZAF,"Population, total",SP.POP.TOTL,16520441.0,16989464.0,17503133.0,18042215.0,18603097.0,19187194.0,...,53145033.0,53873616.0,54729551.0,55876504.0,56422274.0,56641209.0,57339635.0,58087055.0,58801927.0,59392255.0
264,Zambia,ZMB,"Population, total",SP.POP.TOTL,3119430.0,3219451.0,3323427.0,3431381.0,3542764.0,3658024.0,...,14744658.0,15234976.0,15737793.0,16248230.0,16767761.0,17298054.0,17835893.0,18380477.0,18927715.0,19473125.0
265,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,3806310.0,3925952.0,4049778.0,4177931.0,4310332.0,4447149.0,...,13265331.0,13555422.0,13855753.0,14154937.0,14452704.0,14751101.0,15052184.0,15354608.0,15669666.0,15993524.0

In [8]:
poblacion.sort_values('2021')

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
245,Tuvalu,TUV,"Population, total",SP.POP.TOTL,5.404000e+03,5.436000e+03,5.471000e+03,5.503000e+03,5.525000e+03,5.548000e+03,...,1.085400e+04,1.091800e+04,1.089900e+04,1.087700e+04,1.085200e+04,1.082800e+04,1.086500e+04,1.095600e+04,1.106900e+04,1.120400e+04
179,Nauru,NRU,"Population, total",SP.POP.TOTL,4.582000e+03,4.753000e+03,4.950000e+03,5.198000e+03,5.484000e+03,5.804000e+03,...,1.044400e+04,1.069400e+04,1.094000e+04,1.118500e+04,1.143700e+04,1.168200e+04,1.192400e+04,1.213200e+04,1.231500e+04,1.251100e+04
188,Palau,PLW,"Population, total",SP.POP.TOTL,9.446000e+03,9.639000e+03,9.851000e+03,1.007600e+04,1.031800e+04,1.056300e+04,...,1.794600e+04,1.780500e+04,1.779600e+04,1.779400e+04,1.781600e+04,1.783700e+04,1.786400e+04,1.791600e+04,1.797200e+04,1.802400e+04
255,British Virgin Islands,VGB,"Population, total",SP.POP.TOTL,7.850000e+03,7.885000e+03,7.902000e+03,7.919000e+03,7.949000e+03,8.018000e+03,...,2.842100e+04,2.865700e+04,2.897100e+04,2.936600e+04,2.973900e+04,3.006000e+04,3.033500e+04,3.061000e+04,3.091000e+04,3.112200e+04
147,St. Martin (French part),MAF,"Population, total",SP.POP.TOTL,4.135000e+03,4.258000e+03,4.388000e+03,4.524000e+03,4.666000e+03,4.832000e+03,...,3.602600e+04,3.563900e+04,3.526100e+04,3.502000e+04,3.481100e+04,3.449600e+04,3.385200e+04,3.312100e+04,3.255300e+04,3.194800e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,Middle income,MIC,"Population, total",SP.POP.TOTL,2.101463e+09,2.129016e+09,2.169685e+09,2.222461e+09,2.275510e+09,2.329439e+09,...,5.354645e+09,5.421202e+09,5.487659e+09,5.552696e+09,5.616265e+09,5.679375e+09,5.740016e+09,5.797828e+09,5.852404e+09,5.901324e+09
140,Low & middle income,LMY,"Population, total",SP.POP.TOTL,2.243861e+09,2.274748e+09,2.318884e+09,2.375260e+09,2.432089e+09,2.489968e+09,...,5.920181e+09,6.001329e+09,6.082433e+09,6.162743e+09,6.242647e+09,6.322861e+09,6.401272e+09,6.477841e+09,6.551590e+09,6.619579e+09
103,IDA & IBRD total,IBT,"Population, total",SP.POP.TOTL,2.298063e+09,2.329593e+09,2.374361e+09,2.431394e+09,2.488885e+09,2.547296e+09,...,5.997942e+09,6.079383e+09,6.160759e+09,6.241292e+09,6.321324e+09,6.401367e+09,6.479097e+09,6.554880e+09,6.628068e+09,6.695398e+09
259,World,WLD,"Population, total",SP.POP.TOTL,3.031565e+09,3.072511e+09,3.126935e+09,3.193509e+09,3.260518e+09,3.328285e+09,...,7.140896e+09,7.229185e+09,7.317509e+09,7.404911e+09,7.491934e+09,7.578158e+09,7.661776e+09,7.742682e+09,7.820982e+09,7.888409e+09
110,Not classified,INX,"Population, total",SP.POP.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
poblacionnew=poblacion.iloc[:,4:67]

In [41]:
print(poblacionnew)

            1960         1961         1962         1963         1964  \
0        54608.0      55811.0      56682.0      57475.0      58178.0
1    130692579.0  134169237.0  137835590.0  141630546.0  145605995.0
2      8622466.0    8790140.0    8969047.0    9157465.0    9355514.0
3     97256290.0   99314028.0  101445032.0  103667517.0  105959979.0
4      5357195.0    5441333.0    5521400.0    5599827.0    5673199.0
..           ...          ...          ...          ...          ...
261     947000.0     966000.0     994000.0    1022000.0    1050000.0
262    5542459.0    5646668.0    5753386.0    5860197.0    5973803.0
263   16520441.0   16989464.0   17503133.0   18042215.0   18603097.0
264    3119430.0    3219451.0    3323427.0    3431381.0    3542764.0
265    3806310.0    3925952.0    4049778.0    4177931.0    4310332.0

            1965         1966         1967         1968         1969  ...  \
0        58782.0      59291.0      59522.0      59471.0      59330.0  ...
1    149742351.0  153955516.0  158313235.0  162875171.0  167596160.0  ...
2      9565147.0    9783147.0   10010030.0   10247780.0   10494489.0  ...
3    108336203.0  110798486.0  113319950.0  115921723.0  118615741.0  ...
4      5736582.0    5787044.0    5827503.0    5868203.0    5928386.0  ...
..           ...          ...          ...          ...          ...  ...
261    1078000.0    1106000.0    1135000.0    1163000.0    1191000.0  ...
262    6097298.0    6228430.0    6368014.0    6515904.0    6673981.0  ...
263   19187194.0   19789771.0   20410677.0   21050540.0   21704214.0  ...
264    3658024.0    3777680.0    3901288.0    4029173.0    4159007.0  ...
265    4447149.0    4588529.0    4734694.0    4886347.0    5044163.0  ...

            2012         2013         2014         2015         2016  \
0       102112.0     102880.0     103594.0     104257.0     104874.0
1    552530654.0  567891875.0  583650827.0  600008150.0  616377331.0
2     30466479.0   31541209.0   32716210.0   33753499.0   34636207.0
3    376797999.0  387204553.0  397855507.0  408690375.0  419778384.0
4     25188292.0   26147002.0   27128337.0   28127721.0   29154746.0
..           ...          ...          ...          ...          ...
261    1807106.0    1818117.0    1812771.0    1788196.0    1777557.0
262   26223391.0   26984002.0   27753304.0   28516545.0   29274002.0
263   53145033.0   53873616.0   54729551.0   55876504.0   56422274.0
264   14744658.0   15234976.0   15737793.0   16248230.0   16767761.0
265   13265331.0   13555422.0   13855753.0   14154937.0   14452704.0

            2017         2018         2019         2020         2021
0       105439.0     105962.0     106442.0     106585.0     106537.0
1    632746296.0  649756874.0  667242712.0  685112705.0  702976832.0
2     35643418.0   36686784.0   37769499.0   38972230.0   40099462.0
3    431138704.0  442646825.0  454306063.0  466189102.0  478185907.0
4     30208628.0   31273533.0   32353588.0   33428486.0   34503774.0
..           ...          ...          ...          ...          ...
261    1791003.0    1797085.0    1788878.0    1790133.0    1786038.0
262   30034389.0   30790513.0   31546691.0   32284046.0   32981641.0
263   56641209.0   57339635.0   58087055.0   58801927.0   59392255.0
264   17298054.0   17835893.0   18380477.0   18927715.0   19473125.0
265   14751101.0   15052184.0   15354608.0   15669666.0   15993524.0

[266 rows x 62 columns]

In [44]:
pais= poblacion.iloc[:,0]

In [45]:
print(pais)

0                            Aruba
1      Africa Eastern and Southern
2                      Afghanistan
3       Africa Western and Central
4                           Angola
                  ...
261                         Kosovo
262                    Yemen, Rep.
263                   South Africa
264                         Zambia
265                       Zimbabwe
Name: Country Name, Length: 266, dtype: object

In [47]:
poblacionnew=poblacionnew.assign(CountryName=pais)

In [48]:
print(poblacionnew)

            1960         1961         1962         1963         1964  \
0        54608.0      55811.0      56682.0      57475.0      58178.0
1    130692579.0  134169237.0  137835590.0  141630546.0  145605995.0
2      8622466.0    8790140.0    8969047.0    9157465.0    9355514.0
3     97256290.0   99314028.0  101445032.0  103667517.0  105959979.0
4      5357195.0    5441333.0    5521400.0    5599827.0    5673199.0
..           ...          ...          ...          ...          ...
261     947000.0     966000.0     994000.0    1022000.0    1050000.0
262    5542459.0    5646668.0    5753386.0    5860197.0    5973803.0
263   16520441.0   16989464.0   17503133.0   18042215.0   18603097.0
264    3119430.0    3219451.0    3323427.0    3431381.0    3542764.0
265    3806310.0    3925952.0    4049778.0    4177931.0    4310332.0

            1965         1966         1967         1968         1969  ...  \
0        58782.0      59291.0      59522.0      59471.0      59330.0  ...
1    149742351.0  153955516.0  158313235.0  162875171.0  167596160.0  ...
2      9565147.0    9783147.0   10010030.0   10247780.0   10494489.0  ...
3    108336203.0  110798486.0  113319950.0  115921723.0  118615741.0  ...
4      5736582.0    5787044.0    5827503.0    5868203.0    5928386.0  ...
..           ...          ...          ...          ...          ...  ...
261    1078000.0    1106000.0    1135000.0    1163000.0    1191000.0  ...
262    6097298.0    6228430.0    6368014.0    6515904.0    6673981.0  ...
263   19187194.0   19789771.0   20410677.0   21050540.0   21704214.0  ...
264    3658024.0    3777680.0    3901288.0    4029173.0    4159007.0  ...
265    4447149.0    4588529.0    4734694.0    4886347.0    5044163.0  ...

            2013         2014         2015         2016         2017  \
0       102880.0     103594.0     104257.0     104874.0     105439.0
1    567891875.0  583650827.0  600008150.0  616377331.0  632746296.0
2     31541209.0   32716210.0   33753499.0   34636207.0   35643418.0
3    387204553.0  397855507.0  408690375.0  419778384.0  431138704.0
4     26147002.0   27128337.0   28127721.0   29154746.0   30208628.0
..           ...          ...          ...          ...          ...
261    1818117.0    1812771.0    1788196.0    1777557.0    1791003.0
262   26984002.0   27753304.0   28516545.0   29274002.0   30034389.0
263   53873616.0   54729551.0   55876504.0   56422274.0   56641209.0
264   15234976.0   15737793.0   16248230.0   16767761.0   17298054.0
265   13555422.0   13855753.0   14154937.0   14452704.0   14751101.0

            2018         2019         2020         2021  \
0       105962.0     106442.0     106585.0     106537.0
1    649756874.0  667242712.0  685112705.0  702976832.0
2     36686784.0   37769499.0   38972230.0   40099462.0
3    442646825.0  454306063.0  466189102.0  478185907.0
4     31273533.0   32353588.0   33428486.0   34503774.0
..           ...          ...          ...          ...
261    1797085.0    1788878.0    1790133.0    1786038.0
262   30790513.0   31546691.0   32284046.0   32981641.0
263   57339635.0   58087055.0   58801927.0   59392255.0
264   17835893.0   18380477.0   18927715.0   19473125.0
265   15052184.0   15354608.0   15669666.0   15993524.0

                     CountryName
0                          Aruba
1    Africa Eastern and Southern
2                    Afghanistan
3     Africa Western and Central
4                         Angola
..                           ...
261                       Kosovo
262                  Yemen, Rep.
263                 South Africa
264                       Zambia
265                     Zimbabwe

[266 rows x 63 columns]

In [49]:
poblacionnew.to_csv('New_POB_TOT')